name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      ##################################################################################################################
      # Clone
      ##################################################################################################################
      - name: Clone
        uses: actions/checkout@v2

      ##################################################################################################################
      # Setup
      ##################################################################################################################
      - name: Setup - JavaScript
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      ##################################################################################################################
      # Restore Cache
      ##################################################################################################################
      - name: Cache - Yarn
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      ##################################################################################################################
      # Build JavaScript
      ##################################################################################################################
      - name: Yarn - install
        run: yarn install --frozen-lockfile

      - name: Yarn - compile
        run: yarn tsc

      - name: Yarn - build
        run: yarn build